name: Build RETH

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      rome_sdk_branch:
        description: 'Branch name for the rome-sdk repository'
        required: false
        default: 'main'
env:
  REF_NAME: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@master
        with:
          path: reth
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Determine SDK branch name'
        id: get_branch_name
        run: |
          # If it's a workflow_dispatch, use the provided branch name
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            SDK_BRANCH_NAME="${{ github.event.inputs.rome_sdk_branch }}"
          else
            SDK_BRANCH_NAME="main"
          fi
          echo "sdk_branch_name=$SDK_BRANCH_NAME" >> $GITHUB_ENV

      - name: 'Checkout SDK repository'
        uses: actions/checkout@master
        with:
          repository: rome-protocol/rome-sdk
          path: rome-sdk
          ref: ${{ env.sdk_branch_name }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Build reth'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          file: reth/Dockerfile
